/* GAMAYUN+ offline-first service worker. Zero dependencies, no build step -
   plain JS, hand-maintained (not generated by _src/build.py). Per the
   canon spec: pre-cache the shell (index.html, gama-core.js, gama.css) so
   the site loads instantly even offline, then cache everything else
   opportunistically as it's actually visited - stale-while-revalidate,
   so a cached response is served immediately while a fresh one updates
   the cache in the background for next time.

   Paths point at the .min.js/.min.css build artifacts (added 2026-07-23,
   Site Cleanup ticket's minify step) since those are what the page
   templates actually request now, not the human-edited source files. */

const CACHE_NAME = "gamayun-shell-v3";
const CORE_ASSETS = ["/", "/index.html", "/js/gama-core.min.js", "/css/gama.min.css"];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(CORE_ASSETS))
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)))
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  // Cross-origin requests (Google Analytics/AdSense, the Bluesky API,
  // fonts) are left alone entirely - this only manages the site's own
  // same-origin assets.
  if (new URL(event.request.url).origin !== self.location.origin) return;

  event.respondWith(
    caches.match(event.request).then((cached) => {
      const network = fetch(event.request)
        .then((response) => {
          if (response && response.ok) {
            const clone = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
          }
          return response;
        })
        .catch(() => cached);
      return cached || network;
    })
  );
});
