/* GAMAYUN+ offline-first service worker. Zero dependencies, no build step -
   plain JS, hand-maintained (not generated by _src/build.py).

   WHY THIS IS NOT PURE STALE-WHILE-REVALIDATE ANY MORE (2026-08-13)

   It used to be `return cached || network` for every same-origin GET. That
   is textbook stale-while-revalidate and it had a brutal practical
   consequence: EVERY deploy took two visits to become visible. The first
   visit after a change always served the old cached asset and merely
   refreshed the cache for next time. Vin would look at the live site after
   a change, see the old thing, and reasonably conclude the work hadn't been
   done. It was caught red-handed here - a rebuilt boot-sequence.min.js
   (2432B on disk) was still being served to the page as the previous 2731B
   copy, overriding even `fetch(..., {cache:"no-store"})`.

   The split now:

   - CODE AND MARKUP (navigations, .html, .js, .css) are NETWORK-FIRST.
     A change is visible on the first visit, which is the only behaviour
     that makes "is it live yet?" a question with an honest answer. The
     cache is still written on every success and still served whenever the
     network fails, so genuine offline use is unchanged.

   - EVERYTHING ELSE (images, fonts, video, json) stays CACHE-FIRST with a
     background refresh. Those are the heavy, rarely-changing bytes that
     made offline-first worth having, and they're the ones where serving
     instantly actually matters.

   Bumping CACHE_NAME still nukes old caches on activate, but the site no
   longer *depends* on someone remembering to bump it for code changes.

   Paths point at the .min.js/.min.css build artifacts (added 2026-07-23,
   Site Cleanup ticket's minify step) since those are what the page
   templates actually request now, not the human-edited source files. */

const CACHE_NAME = "gamayun-shell-v4";
const CORE_ASSETS = ["/", "/index.html", "/js/gama-core.min.js", "/css/gama.min.css"];

/** Code and markup: must never be served stale on a first visit. */
function isCodeOrMarkup(request, url) {
  if (request.mode === "navigate") return true;
  return /\.(html|js|css)$/i.test(url.pathname);
}

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(CORE_ASSETS)));
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)))
    )
  );
  self.clients.claim();
});

function cachePut(request, response) {
  if (response && response.ok) {
    const clone = response.clone();
    caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
  }
  return response;
}

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  // Cross-origin requests (Google Analytics/AdSense, the Bluesky API,
  // fonts) are left alone entirely - this only manages the site's own
  // same-origin assets.
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  if (isCodeOrMarkup(event.request, url)) {
    // Network-first. Falling back to cache on failure is what keeps the
    // site genuinely usable offline; the difference from before is only
    // that a WORKING network always wins.
    event.respondWith(
      fetch(event.request)
        .then((response) => cachePut(event.request, response))
        .catch(() => caches.match(event.request).then((cached) => cached || Response.error()))
    );
    return;
  }

  // Everything else: cache-first, refreshed in the background.
  event.respondWith(
    caches.match(event.request).then((cached) => {
      const network = fetch(event.request)
        .then((response) => cachePut(event.request, response))
        .catch(() => cached);
      return cached || network;
    })
  );
});
